# Generated by Django 3.1 on 2020-10-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter06', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='gender',
            field=models.IntegerField(),
        ),
    ]
