# Generated by Django 3.1 on 2020-10-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter06', '0002_auto_20201007_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')]),
        ),
    ]
