# Generated by Django 3.1 on 2020-10-19 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapter06', '0006_author_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('monster_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='chapter06.monstertype')),
            ],
        ),
    ]
